version: '3'

services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    volumes:
      - ./frontend:/app
